### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by hcguersoy** [yunuscadirci/CallStranger#14]
Merhaba Yunus,

I'm running into a `IndexError: list index out of range` on my MBP then I try to scan in my home network.

Installed python and libs:

```
❯ python --version
Python 3.7.4
❯ pip3 list
Package      Version
------------ ----------
certifi      2020.4.5.2
cffi         1.14.0
chardet      3.0.4
cryptography 2.9.2
idna         2.9
pip          19.0.3
pycparser    2.20
requests     2.23.0
setuptools   40.8.0
six          1.15.0
termcolor    1.1.0
urllib3      1.25.9
```

Then starting I run into an error:
```
python CallStranger.py
...
Stranger Host: http://20.42.105.45
Stranger Port: 80
Traceback (most recent call last):
  File "CallStranger.py", line 113, in <module>
    devices = upnp.discover()
  File "/Users/hag/workspaces/others/CallStranger/upnpy/upnp/UPnP.py", line 33, in discover
    for device in self.ssdp.m_search(discover_delay=delay, st='upnp:rootdevice', **headers):
  File "/Users/hag/workspaces/others/CallStranger/upnpy/ssdp/SSDPRequest.py", line 49, in m_search
    devices = self._send_request(self._get_raw_request())
  File "/Users/hag/workspaces/others/CallStranger/upnpy/ssdp/SSDPRequest.py", line 100, in _send_request
    device = SSDPDevice(addr, response.decode())
  File "/Users/hag/workspaces/others/CallStranger/upnpy/ssdp/SSDPDevice.py", line 83, in __init__
    self._get_type_request()
  File "/Users/hag/workspaces/others/CallStranger/upnpy/ssdp/SSDPDevice.py", line 21, in wrapper
    return func(device, *args, **kwargs)
  File "/Users/hag/workspaces/others/CallStranger/upnpy/ssdp/SSDPDevice.py", line 128, in _get_type_request
    device_type = root.getElementsByTagName('deviceType')[0].firstChild.nodeValue
IndexError: list index out of range
~/workspaces/others/CallStranger master ❯
```

I run this on macOS 10.15.5, tried it with enabled and disabled firewall.

edit: used commit `8280064` from `master`.

**Comment by yunuscadirci** [comment]
Hi there are too many devices. I broaded exception handling. can you try again?
