### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 2004seraph** [yunuscadirci/CallStranger#28]
I try to scan my home network but this error keeps coming up:
Traceback (most recent call last):
  File "D:\Programming\WongoMessenger\wongoIM.pyw", line 15, in <module>
    upnp.discover()
  File "D:\Programming\WongoMessenger\upnpy\upnp\UPnP.py", line 33, in discover
    for device in self.ssdp.m_search(discover_delay=delay, st='upnp:rootdevice', **headers):
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPRequest.py", line 50, in m_search
    devices = self._send_request(self._get_raw_request())
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPRequest.py", line 100, in _send_request
    device = SSDPDevice(addr, response.decode())
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPDevice.py", line 87, in __init__
    self._get_services_request()
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPDevice.py", line 23, in wrapper
    return func(device, *args, **kwargs)
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPDevice.py", line 54, in wrapper
    return func(instance, *args, **kwargs)
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPDevice.py", line 173, in _get_services_request
    device_services[parsed_service_id] = self.Service(
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPDevice.py", line 259, in __init__
    self._get_actions_request()
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPDevice.py", line 39, in wrapper
    return func(service, *args, **kwargs)
  File "D:\Programming\WongoMessenger\upnpy\ssdp\SSDPDevice.py", line 331, in _get_actions_request
    argument_name = argument.getElementsByTagName('name')[0].firstChild.nodeValue
IndexError: list index out of range
[Finished in 1.0s with exit code 1]

Here's my code:
`
upnp = upnpy.UPnP()`
`upnp.discover()
`

**Comment by yunuscadirci** [comment]
Hi
it looks like a network error.
