### ISSUE TITLE
[Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by mplogas** [yunuscadirci/CallStranger#5]
Affected System: WSL2 Ubuntu 18.04 LTS, RaspBian Buster

Issue: [Errno 11] Resource temporarily unavailable

Steps to reproduce:
1. Install requirements as per documentation
	```sudo pip3 install -r requirements.txt```
2. Run script ```python3 Callstranger.py```
3. Script aborts with error

Log: 
```
Stranger Host: http://20.42.105.45
Stranger Port: 80
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CallStranger.py", line 113, in <module>
    devices = upnp.discover()
  File "/home/mplogas/CallStranger/upnpy/upnp/UPnP.py", line 33, in discover
    for device in self.ssdp.m_search(discover_delay=delay, st='upnp:rootdevice', **headers):
  File "/home/mplogas/CallStranger/upnpy/ssdp/SSDPRequest.py", line 49, in m_search
    devices = self._send_request(self._get_raw_request())
  File "/home/mplogas/CallStranger/upnpy/ssdp/SSDPRequest.py", line 100, in _send_request
    device = SSDPDevice(addr, response.decode())
  File "/home/mplogas/CallStranger/upnpy/ssdp/SSDPDevice.py", line 82, in __init__
    self._get_description_request(utils.parse_http_header(response, 'Location'))
  File "/home/mplogas/CallStranger/upnpy/ssdp/SSDPDevice.py", line 115, in _get_description_request
    device_description = utils.make_http_request(url).read()
  File "/home/mplogas/CallStranger/upnpy/utils.py", line 80, in make_http_request
    return urllib.request.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11] Resource temporarily unavailable>
```

**Comment by Keridos** [comment]
Having almost the same error here, but instead of "Resource temporarlily unavailable" I get "Invalid Argument"

**Comment by yunuscadirci** [comment]
I updated UPnP stack to handle exceptions. can you retry?

**Comment by mplogas** [comment]
Hi @yunuscadirci, this particular error has been resolved but I'm running into a different error now:

```
!Error: http://<local ip>:8080/description.xml failed
Traceback (most recent call last):
  File "CallStranger.py", line 113, in <module>
    devices = upnp.discover()
  File "/home/mplogas/CallStranger/upnpy/upnp/UPnP.py", line 33, in discover
    for device in self.ssdp.m_search(discover_delay=delay, st='upnp:rootdevice', **headers):
  File "/home/mplogas/CallStranger/upnpy/ssdp/SSDPRequest.py", line 49, in m_search
    devices = self._send_request(self._get_raw_request())
  File "/home/mplogas/CallStranger/upnpy/ssdp/SSDPRequest.py", line 100, in _send_request
    device = SSDPDevice(addr, response.decode())
  File "/home/mplogas/CallStranger/upnpy/ssdp/SSDPDevice.py", line 81, in __init__
    self._get_description_request(utils.parse_http_header(response, 'Location'))
  File "/home/mplogas/CallStranger/upnpy/ssdp/SSDPDevice.py", line 114, in _get_description_request
    device_description = utils.make_http_request(url).read()
AttributeError: 'NoneType' object has no attribute 'read'
```

The device that is behind the (redacted) IP and causing the error is my main home automation device. Want me to create a new issue instead?

**Comment by yunuscadirci** [comment]
Hi there are too many devices. I broaded exception handling. can you try again?

**Comment by mplogas** [comment]
Hi @yunuscadirci thanks for your hard work. It seems we're getting close:

```
Stranger Host: http://20.42.105.45
Stranger Port: 80
!Error: http://<local ip>:8080/description.xml failed
!Error in device description request http://<local ip>:8080/description.xml
!Error in  ('<local ip>', 1900)
!Error in service definition http://<other local ip> urn:schemas-upnp-org:service:dummy:1
25  devices found:

 None None ( http://<local ip>:8080/description.xml )
Traceback (most recent call last):
  File "CallStranger.py", line 120, in <module>
    print(colored('\n  ' +str(len(tmpservices)) + ' service(s) found for '+device.friendly_name,'yellow'))
TypeError: must be str, not NoneType
```

I wonder why the script looks for a description.xml on port 8080 of <local ip> instead of port 80? I can GET the description.xml on port 80.

**Comment by yunuscadirci** [comment]
location header points port 8080. can you try with latest commit

**Comment by mplogas** [comment]
@yunuscadirci Awesome, I tried with the latest commit and got a couple of results. Out of 26 devices found, I got 3 vulnerable devices (with total 36 vulnerable services) and 36 unverfied services on 5 devices. Is there a hard limit on the services iterator (36) or is it just pure coincidence?

**Comment by yunuscadirci** [comment]
It is good to see it worked. server verification limit is 50 but i will remove it soon
